### ISSUE TITLE
Intervals on clients tasksheet

### ISSUE THREAD

**Issue by suliatis** [dodie/time-admin#57] opened 2016-12-05 15:03 UTC
Clients should be able to query bigger intervals than one month on "Tasksheet" page, similarly to "Tasksheet Summary" page. The scale of the tasksheet would change dynamically based on the size of the selected interval.

**Comment by dodie** [comment] 2016-12-11 21:27
Duplicate of #58.

**Closed as completed by dodie** 2016-12-11 21:27 UTC
Labels: duplicate, enhancement
